angular.module('app',['ui.router','ngCookies','validation']).config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
		$stateProvider.state('main',{
			url:'/main',
			templateUrl:'view/main.html',
			controller:'mainCtrl'
		})
		.state('position',{
			url:'/position/:id',
			templateUrl:'view/position.html',
			controller:'positionCtrl'
		})
		.state('company',{
			url:'/company/:id',
			templateUrl:'view/company.html',
			controller:'positionClassCtr'
		})
		.state('search',{
			url:'/search',
			templateUrl:'view/search.html',
			controller:'searchCtr'
		})
		.state('login',{
			url:'/login',
			templateUrl:'view/login.html',
			controller:'loginCtr'
		})
		.state('register',{
			url:'/register',
			templateUrl:'view/register.html',
			controller:'registerCtr'
		})
		.state('my',{
			url:'/my',
			templateUrl:'view/my.html',
			controller:'myCtr'
		})
		;
		$urlRouterProvider.otherwise('main');
}]);